# -*- coding: utf-8 -*-
"""Esercizi Lezione 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140Sapl0oXuGh0BziGHOJ9UhIgws5eCSj

# Esercizi Lezione 1

## Operazioni di assegnazione - variabili
"""

a = 5
b = 2.98
c = "Python"

stringa = 'questa è una stringa'

"""## Operazione di output - print()"""

print(a)
print(b)
print(c)
print(stringa)

a = 5
print(a)
a  = 6
print(a)

print(a,b,c)

print(c,b,a)

print("Ciao sto imparando python")

n1 = 10
n2 = 20
print(f"Il contenuto della prima variabili è {n1} e il contenuto della seconda variabile è {n2}")

print("Il contenuto della prima variabile è", n1, "il contenuto della seconda variabile è", n2)

stringa1= "Il contenuto della prima variabile è"
stringa2="il contenuto della seconda variabile è"
print(stringa1, n1, stringa2, n2)